# Generated by Django 6.0.4 on 2026-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='street',
            field=models.CharField(default=123, max_length=256),
            preserve_default=False,
        ),
    ]
