# Generated by Django 6.0.4 on 2026-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
