# Generated by Django 6.0.4 on 2026-06-18 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=231, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shipping.shipping'),
            preserve_default=False,
        ),
    ]
